SocBoot:
  DataSource:
    Master:
      Type: mysql
      DBUrl: root:mysqldev@127.0.0.1:3306/dbname?charset=utf8mb4&parseTime=True&loc=Local
  Redis:
    Master:
      Host: 127.0.0.1
      Port: 6379
      Password: ""
      Database: 0
      MaxIdle: 10
      MaxActive: 30
      ConnectTimeout: 0
      ReadTimeout: 0
      WriteTimeout: 0
  Logger:
    Default:
      LogPath: ./../logs/log.log
      Level: info
      IsSyncConsoleOut: true
      FileSize: 1024
      MaxBackups: 20
      Tag: ddd
    RR:
      LogPath: ./../logs/rr.log
      Level: info
      IsSyncConsoleOut: true
      FileSize: 1024
      MaxBackups: 20
      Tag: rr
  Kafka:
    NameServers: 192.168.1.181:9092
    ReconsumeTimes: 3
  ElasticSearch:
    ServerUrls: ["http://192.168.1.152:9200"]
    Auth:
      UserName: ""
      Password: ""



AppParams:
  Test: test


